### ISSUE TITLE
Transition away from deprecated request package

### ISSUE THREAD

**Issue by Vimux** [editorconfig-checker/editorconfig-checker.javascript#140]
Just a friendly reminder that the `request` package has been deprecated: [request/request#3142 (comment)](https://github.com/request/request/issues/3142#issuecomment-584745385). Additionally, its latest published version, `2.88.2`, adds a deprecation warning whenever it is npm-installed.

Alternatives have been listed at: [request/request#3143](https://github.com/request/request/issues/3143)

**Comment by mstruebing** [comment]
Thank you for creating that issue.
Do you plan to work on it? - That would be super cool :)

**Comment by Vimux** [comment]
No, I did not plan to work on this, unfortunately. So, yes, this is just a reminder from me.

**Comment by mstruebing** [comment]
Thanks, that's also great! :)
I will have a look soon.
