### ISSUE TITLE
Default ignores does not work?

### ISSUE THREAD

**Issue by nicothin** [editorconfig-checker/editorconfig-checker.javascript#18]
![image](https://user-images.githubusercontent.com/3499680/33706404-1bb3c1d8-db45-11e7-8e9d-d10535440f73.png)

(Win10, node 8.9.2)

**Comment by mstruebing** [comment]
Hey thanks for your issue.
I will try  to fix the issue soon.

**Comment by mstruebing** [comment]
@nicothin hope your issue is resolved with this.
If not feel free to reopen.
