### ISSUE TITLE
Feature Request: exclude `node_modules` from being checked by default

### ISSUE THREAD

**Issue by andrewvasilchuk** [editorconfig-checker/editorconfig-checker.javascript#192]

**Comment by mstruebing** [comment]
@andrewvasilchuk thank you very much for your issue.
But shouldn't that already be the case? Could you provide more information how did you have used the tool?

**Comment by andrewvasilchuk** [comment]
@mstruebing, It's kinda strange. I used the package approximately 1 month ago and I had to exclude `node_modules` and `.git` folders from being checked. But when I've installed it yesterday these folders was excluded by default.

I guess, we can close the issue.
