### ISSUE TITLE
File-specific properties ignored

### ISSUE THREAD

**Issue by InzeNL** [editorconfig-checker/editorconfig-checker.javascript#209]
Will test some more and report more on this:

indent_size seems to be verified from the `[*]` section, and not the file-specific properties.
E.g.
```
[*]
indent_size = 4

[{*.yaml, *.yml}]
indent_size = 2
```
When a yml file has an indent_size of 2, it will throw an error `Wrong amount of left-padding spaces(want multiple of 8)``

Along with that, I've unset a variable for some filetypes, but it doesn't seem to ignore these properties.
E.g.
```
[*]
max_line_length = 120

[.editorconfig]
max_line_length = unset
```
If a line in .editorconfig is longer that 120, it will throw an error `Line to long (X instead of 120)` (which should also be "too," but I can live with that)

**Comment by mstruebing** [comment]
Hey @InzeNL thank you very much for your issue. :rocket: 

For the first part I think your glob pattern is wrong. If you adopt the examples from https://editorconfig.org/ you can see it should be:

```
[*.{yaml,yml}]
indent_size = 2
```

Could you test it that would work?

For the second one:
sure that shouldn't be an error and should be fixed, thank you :+1:

**Comment by InzeNL** [comment]
@mstruebing 
I tested the change, and the same errors occur
I also tested defining `.travis.yml` directly, and even that seems to be giving errors.

I just downloaded the binary from the Go-repository, and noticed it's not actually this wrapper causing these errors, so I'll be creating a ticket in that repo as well

**Comment by InzeNL** [comment]
https://github.com/editorconfig-checker/editorconfig-checker/issues/123

**Comment by mstruebing** [comment]
Closed as this is an issue in the main repository.
