### ISSUE TITLE
Disable rules inline

### ISSUE THREAD

**Issue by AndyOGo** [editorconfig-checker/editorconfig-checker.javascript#22]
It would be awesome to be able to disable certain rules through inline comments.

Different comment's syntax is quite challenging, though it would be awesome.

**Comment by mstruebing** [comment]
A very good idea actually, I will think about how to implement it. Thank you

**Comment by mstruebing** [comment]
Hey @AndyOGo 
could you play with the PR #24 if this does anything you wanted in this issue?

It should be simply  enough to add `editorconfig-disable-line` at the end of a line
