### ISSUE TITLE
Works incorrectly with paths

### ISSUE THREAD

**Issue by Alecto** [editorconfig-checker/editorconfig-checker.javascript#387]
Hello! Please help me figure out how to exclude several folders from the scan.

documentation says to use valid regular expressions
![image](https://user-images.githubusercontent.com/8464662/183348808-74ff6d76-46b5-477e-948e-1575a11a3148.png)

with one folder - exception works
![image](https://user-images.githubusercontent.com/8464662/183348896-1743d6c7-3b79-474d-bb52-75b1e2b53282.png)

but if I use a valid regular expression - the plugin doesn't work
![image](https://user-images.githubusercontent.com/8464662/183349018-dc49b517-6ef1-4ee2-9012-d07a06da4448.png)
path not found as the result
![image](https://user-images.githubusercontent.com/8464662/183349197-392b9328-3334-4695-a3be-a1e4b8429de6.png)

please explain where I went wrong and how to set an exception for a group of certain files or folders.

**Comment by mstruebing** [comment]
Can you try:

```
    "editorconfig": "editorconfig-checker -exclude 'libs|styles\\.css'"
```

I think it has to do with how npm/node interprets the script command.

**Comment by Alecto** [comment]
@mstruebing doesnt work
![image](https://user-images.githubusercontent.com/8464662/183365306-6863b087-6111-4bff-85ec-cb80cb31302d.png)

and if I leave only the folder - it doesn't work either
![image](https://user-images.githubusercontent.com/8464662/183365452-92b3e574-8693-433e-9f2a-11452a23ef8a.png)

the impression is that the regular expression is not perceived at all, only the simplest string.

**Comment by mstruebing** [comment]
For me it works:

https://user-images.githubusercontent.com/12071529/183366955-cb34e0f3-d405-4fa8-98e1-da1b9e9e13ae.mov

**Comment by mstruebing** [comment]
Uhhh, sorry, I just realized: it looks like you are on windows by the path your terminal shows?
I don't really have a clue about windows development and don't have a machine to test.

**Comment by Alecto** [comment]
that's how it works
![image](https://user-images.githubusercontent.com/8464662/183367670-2084f49f-cf95-4351-ae76-304af6f4b916.png)

but if you put '...' - it stops working
![image](https://user-images.githubusercontent.com/8464662/183368119-1c3ff5b2-696a-4459-8ad7-caed1c8d6938.png)

even if you specify one folder, but in quotes - it no longer works
![image](https://user-images.githubusercontent.com/8464662/183368307-52267caa-5d85-45d0-a64e-2f63f5314c8b.png)



![image](https://user-images.githubusercontent.com/8464662/183367873-18fc99db-cff6-44b8-a2cf-758991146d39.png)


![image](https://user-images.githubusercontent.com/8464662/183368703-5ceef03b-8e94-40fd-b7a7-a043ec38a3d5.png)
![image](https://user-images.githubusercontent.com/8464662/183368761-f9b296b5-1058-4642-ac73-e1cddd48f82a.png)

**Comment by jerone** [comment]
It looks like any paths are incorrectly being mapped. Also the paths in `.editorconfig` file itself.

With the following (part of) `.editorconfig`:
```
[tests/**.ts]
trim_trailing_whitespace = false
```

It should not give the following errors:
![image](https://user-images.githubusercontent.com/55841/184448318-468b9704-b545-4c76-a265-595802e2e2c4.png)

**Comment by rasa** [comment]
I don't know it's it required in this context, but the regex
```
libs|styles\\.css
```
may need parentheses:
```
(libs|styles\\.css)
```
Also, I don't know if it applies here, but Windows' CMD.EXE needs the double quote character (instead of the apostrophe) to surround strings. So can you try:
```txt
"editorconfig-checker -exclude \"(libs|styles\\.css)\""
```

**Comment by Alecto** [comment]
@rasa 
Thanks a lot, it looks like your solution works! I'll check with a fresh mind, but so far I've managed to ignore files and folders! thanks again.

**Comment by rasa** [comment]
@Alecto Great news! If it's solved your issue, please close this ticket if you don't mind. Thanks.

**Comment by rasa** [comment]
@jerone Your [fix](https://github.com/jerone/eslint-plugin-angular-template-consistent-this/commit/f0dfeb3279a85f1dc7f903b1287b904c9325a889) changes `\\` to `/` in the `.editorconfig` file. Is this the issue you are raising? That editorconfig-checker handles `/`s properly, but fails on treating `\\` as a valid directory separator on Windows?

If that is the case, note that https://spec.editorconfig.org/#file-format says:
"Backslashes (\\) are not allowed as path separators (even on Windows)."

**Comment by jerone** [comment]
> @jerone Your [fix](https://github.com/jerone/eslint-plugin-angular-template-consistent-this/commit/f0dfeb3279a85f1dc7f903b1287b904c9325a889) changes `\\` to `/` in the `.editorconfig` file. Is this the issue you are raising? That editorconfig-checker handles `/`s properly, but fails on treating `\\` as a valid directory separator on Windows?

Aldo this was an half year ago, I think that "fix" was an test to see editorconfig-checker in action. 
The issue at that time, was that it would not handle **any** path separators. See https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/387#issuecomment-1237329381 If that is still an issue, I have no idea.
