### ISSUE TITLE
node-fetch@2.6.7 security vulnerable library

### ISSUE THREAD

**Issue by redwoodxiao** [editorconfig-checker/editorconfig-checker.javascript#388]
└─┬ editorconfig-checker@4.0.2
  └── node-fetch@2.6.7 

similar issue 

https://github.com/lquixada/cross-fetch/issues/143

**Comment by katsoohoo** [comment]
Can we get an estimate on when this issue will be addressed?

**Comment by katsoohoo** [comment]
Hello again, can we get an update for this vulnerability fix?

**Comment by theoludwig** [comment]
This issue have been fixed with the latest v5 versions.
Thanks for reporting!
