### ISSUE TITLE
Sync NPM and GitHub

### ISSUE THREAD

**Issue by aslafy-z** [editorconfig-checker/editorconfig-checker.javascript#393]
The [NPM package](https://www.npmjs.com/package/editorconfig-checker) was upgraded to 5.0.1 where this repository sticks to 4.0.2.
Can you publish the code change please?

**Comment by mstruebing** [comment]
Hey, what advantages do we have when using GitHub releases for this package?
Wouldn't everyone install this via npm anyway?

**Comment by aslafy-z** [comment]
It's a matter of being able to review changes. Check the changelog section for this dependabot PR: https://github.com/aslafy-z/helm-git/pull/237. I'm not that comfortable into merging a major bump without any informations.

**Comment by mstruebing** [comment]
Would be good to have some kind of release automation.
i.e. push a tag and do an npm publish and create a github release + automatic change log generation.

Feel free to provide a PR if you feel comfortable doing this.

**Comment by jerone** [comment]
In addition to review the changes, people can subscribe to release changes here in GitHub and get notified, but not on NPM.

**Comment by jerone** [comment]
Something weird going on... why publish version 1.5.0 ?
![image](https://github.com/editorconfig-checker/editorconfig-checker.javascript/assets/55841/f7e1c490-eb6b-43a0-a609-c794ed5e7684)

**Comment by mstruebing** [comment]
@theoludwig do you know?
