### ISSUE TITLE
Duplicate errors

### ISSUE THREAD

**Issue by firefoxic** [editorconfig-checker/editorconfig-checker.javascript#397]
Hi!

For some reason every error is duplicated in both declarations and total counts.

![image](https://user-images.githubusercontent.com/3382798/235370815-dfcf8476-3d46-464c-b8ad-acf7c6686de0.png)

**Comment by theoludwig** [comment]
Hey! :wave:

I think this issue is fixed with https://github.com/editorconfig-checker/editorconfig-checker/commit/a49a2ff72e0d15e57ca40956a504ad6132dbfada.
