### ISSUE TITLE
Builds v5.0.0-5.1.1 include lots of suspicious looking, unnecessary code

### ISSUE THREAD

**Issue by mgdodge** [editorconfig-checker/editorconfig-checker.javascript#402]
Looking at upgrading a project that is using 4.0.2, and I noticed the 5.x releases were out. Trying to find the change log, I noticed that npmjs.com lists a steady increase in file size. Got suspicious, and it looks like the dist includes a ton of stuff that doesn't belong there!

4.0.2 - 19.5kB: 2 small js files plus standard package.json/README/LICENSE/CHANGELOG files
5.0.0 - 782kB: a dist folder with a single 776kB index.js, looks like it has graphql clients, fetch wrappers, lots of other stuff included
5.0.1 - 782kB: similar to 5.0.0
5.1.0 - 3.27MB: dist folder includes 3.17MB index.js, setup-node-sandbox.js, setup-sandbox.js, events.js, bridge.js, 37.index.js, all sorts of strange code in them.
5.1.1 - 3.27MB: similar to 5.1.0

Even if the extra code wasn't suspicious and the actual utility ran fine, I am not willing to introduce 3MB into my repos!

Please investigate what is causing this, clean up the build, and release a version which doesn't look like a security nightmare.

**Comment by mstruebing** [comment]
@mgdodge thanks for your issue. 
Feel free to open a PR which brings us into a better situation.

The main thing that would be responsible for this is the introduction of `ncc` to build our code I think.
It has some advantages and one of their disadvantages would be that it's adding a bit of code overhead.

The GraphQL client/fetch wrappers from 5.0.0 are actually needed because we do not hardcode the version anymore but fetch it from GitHub.

If you do not want to introduce the overhead of this wrapper in your repositories feel free to use the core binary (which will be downloaded by this wrapper anyway): https://github.com/editorconfig-checker/editorconfig-checker

**Comment by theoludwig** [comment]
Opened a PR (#404) to minify `ncc build` output, it reduces by half the package size.

Before:
```sh
ncc: Version 0.38.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@5.2.2 (local user-provided)
  10kB  dist/37.index.js
3005kB  dist/index.js
3015kB  [3320ms] - ncc 0.38.1
```

After:
```sh
ncc: Version 0.38.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@5.2.2 (local user-provided)
  10kB  dist/37.index.js
1872kB  dist/index.js
1882kB  [4502ms] - ncc 0.38.1
````

We could reduce it even further by removing `node-fetch` and `proxy-agent` dependencies (`proxy-agent` being the bottleneck).
By doing so:
```sh
ncc: Version 0.38.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@5.2.2 (local user-provided)
566kB  dist/index.js
566kB  [2730ms] - ncc 0.38.1
```

Should we consider dropping support for HTTP Proxies, what are the use cases for those? Ref: https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/394
Also, latest v20 Octokit release dropped support for it aswell: https://github.com/octokit/rest.js/releases/tag/v20.0.0

Mind to share your uses cases for HTTP Proxies? @nejch @bufferoverflow @dlouzan @antoineauger
Thanks! :smile:

**Comment by nejch** [comment]
@theoludwig +1 with the comment above, proxies are common in large organizations and the point of this wrapper is a convenience to download the go binary in a node project, and it would be strange if it can't do that one single job.

For users who care about security they presumably already pin their versions and use lockfiles to audit version bumps. If supply chain attacks are still a concern IMO it makes more sense to fetch only the go binary directly.

A better way might be to find a smaller agent library (that still supports the standard proxy environment variables).

**Comment by theoludwig** [comment]
Okay, understandable, HTTP Proxy is a useful feature to have. :+1:
We'll need to find a way to update GitHub Octokit >= v20 without losing this feature (ref: https://github.com/octokit/rest.js/issues/43).
And also how we could reduce the package size.

**Comment by nejch** [comment]
Hmm, and it actually seems like 5.1.2 has already broken proxy support again, I'll wait for some more renovate PRs on our repos and see if its reproducible everywhere and report back in an issue.

**Comment by theoludwig** [comment]
> it actually seems like 5.1.2 has already broken proxy support again

I'm sorry to hear that, we should fix it ASAP.
We should probably have automated tests with CI, to ensure that it continues to work when doing changes to the project.

**Comment by nejch** [comment]
https://github.com/editorconfig-checker/editorconfig-checker.javascript/pull/407 should fix the proxies and just happens to remove some of the libraries so everyone should be happy here hopefully :sweat_smile:
