### ISSUE TITLE
5.1.2 no longer supports HTTP proxy

### ISSUE THREAD

**Issue by nejch** [editorconfig-checker/editorconfig-checker.javascript#405]
Just to confirm https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/402#issuecomment-1816391363, 5.1.2 no longer downloads the go binary via proxy:

```
$ yarn lint:editorconfig
yarn run v1.22.19
$ editorconfig-checker docs/*/*.md docs/*.md *.md
Failed to download binary:
HttpError: fetch failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

(follow-up to https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/394)

We re-added this earlier this year in https://github.com/editorconfig-checker/editorconfig-checker.javascript/pull/395, so might just need some tweaking.

/cc @theoludwig

**Comment by theoludwig** [comment]
Thanks for creating the issue! @nejch 

I don't know how I could test it myself, I don't have a HTTP Proxy to test.
And the code haven't changed much in relation of ProxyAgent and related, only dependencies update, might be related that we updated `proxy-agent` and related dependencies.

Would be much appreciated if someone could:
1. Add a automated test so it doesn't happen again, and we do changes "fearlessly" (or at least less in the blind)
2. Fix the problem.

**Comment by theoludwig** [comment]
Do you think, it's related to `--minify` with [vercel/ncc](https://github.com/vercel/ncc)?

**Comment by nejch** [comment]
I'll try to take a look when I find some time. I was considering adding those in the initial PR but I think there were no tests yet at the time.

I agree it could be something to do with the major bumps in the agent library.
