### ISSUE TITLE
Release v1.5.0 should be release v5.1.5

### ISSUE THREAD

**Issue by theoludwig** [editorconfig-checker/editorconfig-checker.javascript#410]
Apparently with the merge of this PR: https://github.com/editorconfig-checker/editorconfig-checker.javascript/pull/409, something went wrong for the Release Process. Maybe because, of the force push?

@mstruebing Do you have any insights to what happened?

**Comment by mstruebing** [comment]
I don’t really know what happened and didn’t had time to investigate - but what I did is I reworded that one commit and force pushed, so I don’t think it should affect older releases?

**Comment by theoludwig** [comment]
> I don’t think it should affect older releases

It doesn't affect older releases, as npm releases are immutable.
However I'm worried about future releases. I don't know what the behavior will be.

**Comment by theoludwig** [comment]
Problem solved: https://github.com/editorconfig-checker/editorconfig-checker.javascript/releases/tag/v5.1.5
Apparently, when you forced push, you made it that the commit of v5.1.4 was not anymore in the `master` branch: https://github.com/editorconfig-checker/editorconfig-checker.javascript/commit/b1748bc31bb5a852c3241884050715a1b86a73ca 

"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

And for `semantic-release` to work, the tag/commit needs to be in the history to consider it: "we ignore tags that are not in the branch history." (ref: https://github.com/semantic-release/semantic-release/issues/1351#issuecomment-549409645).

The solution, was to delete, the v5.1.4 release/tag, and recreate it, with the commit on `master`.

**Comment by mstruebing** [comment]
Ouch, much thanks for investigating and sorry for the inconvenience
