### ISSUE TITLE
Zero IS a multiple of 4!

### ISSUE THREAD

**Issue by mcandre** [editorconfig-checker/editorconfig-checker.javascript#46]
editorconfig-checker does this weird thing where it often demands that lines be super duper indented, when I really want them at the very left margin.

```console
177) ./yi.hs
	1: Not the right amount of left-padding spaces (found 0 expected multiple of 4 # bash8)
	3: Not the right amount of left-padding spaces (found 0 expected multiple of 4 # bash8)
	5: Not the right amount of left-padding spaces (found 0 expected multiple of 4 # bash8)
	6: Not the right amount of left-padding spaces (found 0 expected multiple of 4 # bash8)
	8: Not the right amount of left-padding spaces (found 0 expected multiple of 4 # bash8)
	10: Not the right amount of left-padding spaces (found 0 expected multiple of 4 # bash8)
```

**Comment by mstruebing** [comment]
Wow!
Cool that you are using it for linting haskell! :)

As I can see, there is a test case which should match exactly your case (https://github.com/editorconfig-checker/editorconfig-checker.javascript/blob/master/src/validation/space/space-validator.test.js#L3)

Could you provide more information of the issue? 
Maybe your `.editorconfig`, directory structure, the file which is wrong and your `package.json` + `yarn.lock`/`package-lock.json`?

**Comment by mstruebing** [comment]
obsolete when #47 is merged
