### ISSUE TITLE
0.0.3 is tagged latest instead of 1.3.3

### ISSUE THREAD

**Issue by simonua** [editorconfig-checker/editorconfig-checker.javascript#49]
Hi @mstruebing, 

Looks like a tagging issue on latest version. I had to install via `npm i editorconfig-checker@1.3.3`.

![image](https://user-images.githubusercontent.com/8005145/51560130-b20ea800-1e51-11e9-86ab-adce6cbbf660.png)

**Comment by mstruebing** [comment]
Hey thanks for reporting this issue.

I tried to release the next-gen version to test it how it would behave, but I've thought that 0.0.3 would don't cause any problems because I'm already at 1.3.3. So, with correct version constraints it should work. But yeah, this is a bug.

Do you have an idea how to fix this?

**Comment by mstruebing** [comment]
It should be fixed by now.
A simple: `npm unpublish editorconfig-checker/0.0.3` was the solution.

Again, thanks for reporting.

**Comment by simonua** [comment]
@mstruebing, you got it! 

![image](https://user-images.githubusercontent.com/8005145/51610428-c3f05980-1eea-11e9-9c17-2ae090296c3a.png)

If you want to test a package without publishing, you can run `npm pack`, which will create a local tgz file. You can then run `npm i <package path>\<filename>.tgz` from a test application to install it. Other ways are just an `npm i <package path>` without prior packing or [`npm link` ](https://docs.npmjs.com/cli/link.html) if you want to continuously develop your package while have it symbolically linked to your test application.

**Comment by mstruebing** [comment]
Wow thanks for letting me know that! :)
Great to have people share their knowledge

**Comment by simonua** [comment]
Of course! We all learn from each other. Cheers!
