### ISSUE TITLE
Add support to exclude files by path

### ISSUE THREAD

**Issue by wturnerharris** [editorconfig-checker/editorconfig-checker.javascript#66]
I'm trying to find out how to exclude a path and its files from validation. This is similar to how the source binary can [exclude](https://github.com/editorconfig-checker/editorconfig-checker#via-arguments) a path, say `node_modules` or `vendor` et al.

I have tried a few combinations, but it does not appear to allow a path to be recognized.

**Comment by mstruebing** [comment]
Hey @wturnerharris you can't currently exclude a component via path. It is possible via regular expressions only.

I think regular expressions are more powerful and give you more flexibility as a path and I don't want to mix regular expressions and paths somehow so I decided to go fully for regular expressions.

I'll close this issue if you have more thoughts on that feel free to add your answer anyway or to open that issue again.

I hope that helps :)
If you need more help please let me know.

**Comment by mstruebing** [comment]
It includes the full path and not only the filename.

You can already use it like: 
`ec --exclude '<REGULAR_EXPRESSION>'` 

i.e in your `package.json`:

```
"lint-editorconfig": "ec --exclude 'LICENSE$|\\.js$'"
```

and `npm run lint-editorconfig` would exclude every file which ends with `LICENSE` or with `.js`.
